### ISSUE TITLE
`except Exception as e:` doesn't work with nim js

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12223]
`except Exception as e:` doesn't work with `nim js`

### Example
`nim js -r $timn_D/tests/nim/all/t0744.nim`
```nim
proc fun() =
  # var z: seq[string] = @[] # sidesteps bug
  var z: seq[string]
  discard z[4]

proc main()=
  try:
    fun()
  # except: # sidesteps bug
  except Exception as e:
    echo "caught"
    echo getCurrentExceptionMsg()

main()
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0744.js:366
                        throw lastJSError;
                        ^

TypeError: Cannot read property 'length' of null
    at fun_327214 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t0744.js:575:36)
    at main_327231 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t0744.js:638:3)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t0744.js:664:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

### Expected Output
```
caught
Cannot read property 'length' of null
```

### Additional Information
* Your Nim version (output of `nim -v`).
recent devel f915064e07c31b0be88bb39553764dd9f1c6c915

* Was it working in the previous Nim releases?
no

**Comment by Araq** [comment]
Strange, I was sure our tests cover that...
