### ISSUE TITLE
unsafeAddr broken in JS for proc parameters

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#14100]
### Example
```nim
proc foo[T](x: T) = # generics doesn't matter here, you can try writing a proc for each type used below
  echo(unsafeAddr(x)[])

foo("hello")
foo(@[1, 2, 3])
foo([1, 2, 3])
foo(1)

import jsconsole

proc consoleFoo[T](x: T) =
  console.log(unsafeAddr(x)[])

consoleFoo("hello")
foo(@[1, 2, 3])
foo([1, 2, 3])
foo(1)
```

### Current Output
```

@[]
[undefined, undefined, undefined]
undefined

1
1
undefined
```

### Expected Output
```
"hello"
@[1, 2, 3]
[1, 2, 3]
1
"hello"
@[1, 2, 3]
[1, 2, 3]
1
```

### Additional Information

* ~~`var x = x` then `addr` fixes all of these.~~ Simply adding `let x = x` also works.
* This was shown in https://github.com/nim-lang/Nim/issues/3104#issuecomment-338967415 but the issue seems to be completely unrelated.
* Works fine for `let` & `for` variables.

```
$ nim -v
Nim Compiler Version 1.2.0
```

**Comment by bung87** [comment]
this was introduced in https://github.com/nim-lang/Nim/commit/61f2f1f5c5c563eefc8388c2b655ac816bcf676c

**Comment by ringabout** [comment]
> this was introduced in [61f2f1f](https://github.com/nim-lang/Nim/commit/61f2f1f5c5c563eefc8388c2b655ac816bcf676c)

No, I guess this never works, Nim v1.0.4 doesn't work too.

**Comment by bung87** [comment]
there's lot changes after v1.0.4, test agains it does not results "never works"

worked version maybe https://github.com/nim-lang/Nim/pull/15078

**Comment by ringabout** [comment]
In Nim 0.19.0
```nim
proc foo[T](x: T) = # generics doesn't matter here, you can try writing a proc for each type used below
  echo(unsafeAddr(x)[])

foo("hello")
foo(@[1, 2, 3])
foo([1, 2, 3])
foo(1)
```
gave:
```

@[]
D:\QQPCmgr\Desktop\Nim\nimcache\test.js:475
    throw new Error(cbuf_15801);
    ^

Error: Error: unhandled exception: index out of bounds [IndexError]
Traceback (most recent call last)
foo.foo, line: 2
$.$, line: 3486
collectionToString.collectionToString, line: 2176

    at unhandledException (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:475:11)
    at raiseException (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:264:3)
    at raiseIndexError (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:490:3)
    at chckIndx (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:284:3)
    at collection_to_string_25683 (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:645:29)
    at HEX24_25674 (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:683:32)
    at foo_25666 (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:694:11)
    at Object.<anonymous> (D:\QQPCmgr\Desktop\Nim\nimcache\test.js:711:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
Error: execution of an external program failed: 'E:\node\node.exe D:\QQPCmgr\Desktop\Nim\nimcache\test.js '
```

**Comment by metagn** [comment]
I don't think there's really a way for this to be "introduced", this is very special behavior that the compiler must account for that I haven't seen implemented. You would have to track whether a proc uses `unsafeAddr` for a parameter, then generate the *function signature* differently depending on it. I think doing that would be dumb, a better way would be to disallow it (which I know we do a lot, but here it makes sense) and tell the user to use a `ptr T` parameter instead.
