### ISSUE TITLE
js: `lent` doesn't work in iterators with tuple destructuring

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14574]
`toTable` doesn't work with js target with values of non-primitive type: Cannot read property 'slice' of undefined
### Example
```nim
import tables
type Foo = object
  a: int
proc fn() =
  let x = Foo(a: 10) # likewise with tuples
  block:
    var t: Table[string, Foo]
    t["abc"] = x # ok
  block:
    let t = {"abc": x}.toTable # bug
fn()
```

### Current Output
nim js -r --lib:lib $timn_D/tests/nim/all/t10893.nim
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:170
        result_33250219 = src_33245024.slice(0);
                                       ^

TypeError: Cannot read property 'slice' of undefined
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:170:40)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:1994:48)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:1999:7)
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:145:7)
    at toTable_34360655 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:2647:13)
    at fn_34271017 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:2673:24)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:2682:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
```

### Expected Output
```
works
```

### Additional Information
* devel 0824fdd06100282a853fa50efb66e2161f4235d8 1.3.5

EDIT:
this works:
```nim
proc toTable2*[A, B](pairs: openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  # for key, val in items(pairs):
  for i in 0..<len(pairs):
    result[pairs[i][0]] = pairs[i][1]
```

so looks like what's broken is items tuple destructuring:

```nim
  proc fn() =
    let a = @[("foo", (12, 13))]
    for (k,v) in a:
      echo (k,v)
  fn()
```
crashes with:
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:198
        result_33250219 = src_33245024.slice(0);
                                       ^

TypeError: src_33245024.slice is not a function
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:198:40)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:366:48)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:371:7)
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:173:7)
    at fn_33627401 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:895:13)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:915:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
```

EDIT: bug disappears if I remove `lent` in iterators.nim
```nim
iterator items*[T](a: seq[T]): lent2 T {.inline.} =
=>
iterator items*[T](a: seq[T]): T {.inline.} =
```

**Comment by timotheecour** [comment]
maybe related:
```nim
when defined case7:
  proc bar[T](a: T): lent T = a
  let a = (10, 11)
  let (k,v) = bar(a)
```
```
$nimb js -r -d:case7 --hint:msgorigin $timn_D/tests/nim/all/t10893.nim
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.nim(80, 31) Error: internal error: genAddr: 2
    proc bar[T](a: T): lent T = a
                                ^
/Users/timothee/git_clone/nim/Nim_prs/compiler/jsgen.nim(1290, 24) compiler msg initiated here [MsgOrigin]
```

**Comment by timotheecour** [comment]
further simplified:
```nim
when true:
  proc bar[T](a: T): lent T = a
  let a = 10
  echo bar(a)
```
Error: internal error: genAddr: 2

(it's an skParam)
EDIT: this one is actually a different bug => moving this to https://github.com/nim-lang/Nim/issues/14576

**Comment by cooldome** [comment]
Does it work if you replace `lent` with `var` and use var variables?

**Comment by timotheecour** [comment]
ya it exercises a different code path;

note: there are actually 2 bugs here and I'm gonna fix 1 of them; 

further reduced from orginal example:
```nim
when defined case6c:
  iterator fn[T](a:T): lent T = yield a
  let a = (10, (11,))
  for (x,y) in fn(a):
    echo (x,y)
```

**Comment by timotheecour** [comment]
this was wrongly closed (see https://github.com/nim-lang/Nim/pull/15078#issuecomment-665136469), the bug is still there (eg https://github.com/nim-lang/Nim/issues/14574#issuecomment-640036557)

**Comment by bung87** [comment]
I can comfirm that all reported as "internal error: genAddr" now fixed , others dont.

**Comment by timotheecour** [comment]
renamed to rescope this issue after some of the bugs were fixed.


```nim
when defined case3b:
  iterator fn[T](a:T): lent T = yield a
  let a = (10, (11,))
  for b in fn(a): echo b

when defined case3c:
  proc fn[T](a:T): lent T = a
  var a = (10, (11,))
  let b = fn(a)
  echo b

when defined case3d:
  proc fn[T](a:T): lent T = a
  var a = (10, (11,))
  let (x,y) = fn(a)
  echo (x,y)
```
only case3b is broken, so it's something about lent + tuple desctructuring in iterator
