### ISSUE TITLE
[ARC] Weird crash after the optimizer PR

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#15024]
This code works with refc on latest devel and with ARC/ORC before the optimizer PR. Initially minimized from https://github.com/Nycto/RBTreeNim/blob/master/tests/t_rbtree.nim#L229

### Example
```nim
type
  Node = ref object
    left, right, parent: Node
    value: int

proc delete(target: var Node) =
  var sibling = target.parent.left
  var saved = sibling.right

  sibling.right = saved.left
  sibling.parent = saved

proc main = 
  var five = Node(value: 5)

  var six = Node(value: 6)
  six.parent = five
  five.right = six

  var three = Node(value: 3)
  three.parent = five
  five.left = three

  var four = Node(value: 4)
  four.parent = three
  three.right = four
  
  echo "doing shady stuff..."
  delete(six)
  # need both of these echos
  echo five.left.value
  echo five.right.value
  
main()
```

### Current Output (gdb)
```
Program received signal SIGSEGV, Segmentation fault.
rawAlloc__mE4QEVyMvGRVliDWDngZCQ (a=0x55555555f0e0 <allocator__Het9ctRSeaVb4hPekZZNCJQ>, requestedSize=41) at /home/dian/Things/Nim/lib/system/alloc.nim:787
787             c.freeList = c.freeList.next
(gdb) bt
#0  rawAlloc__mE4QEVyMvGRVliDWDngZCQ (a=0x55555555f0e0 <allocator__Het9ctRSeaVb4hPekZZNCJQ>, requestedSize=41) at /home/dian/Things/Nim/lib/system/alloc.nim:787
#1  0x0000555555559d2a in alloc__UxtcZ3QOXKsB7mMchxUf9cg (size=41, allocator=0x55555555f0e0 <allocator__Het9ctRSeaVb4hPekZZNCJQ>)
    at /home/dian/Things/Nim/lib/system/alloc.nim:1081
#2  allocImpl__KzdpcuLT9aef9bsiSHlIu9aFg_2 (size=41) at /home/dian/Things/Nim/lib/system/alloc.nim:1031
#3  allocSharedImpl (size=41) at /home/dian/Things/Nim/lib/system/alloc.nim:1078
#4  allocShared0Impl__KzdpcuLT9aef9bsiSHlIu9aFg (size=41) at /home/dian/Things/Nim/lib/system/alloc.nim:1081
#5  rawNewString (space=32) at /home/dian/Things/Nim/lib/system/strs_v2.nim:96
#6  nimIntToStr (x=6) at /home/dian/Things/Nim/lib/system/strmantle.nim:70
#7  0x000055555555b023 in main__x7KsK5PImePstp1Xyet9clw () at /home/dian/Stuff/RBTreeNim/src/rbtree2.nim:32
#8  0x000055555555b359 in NimMainInner () at /home/dian/Stuff/RBTreeNim/src/rbtree2.nim:8
#9  0x000055555555510d in main (argc=<optimized out>, args=<optimized out>, env=<optimized out>) at /home/dian/Things/Nim/lib/system.nim:2141
```

### Expected Output
```
3
6
```

### Additional Information
I'm not sure, but it might be a cursorifier bug. I couldn't confirm that because there's no way to turn it off.

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-07-20
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 70acba7f0d4d73bce941dbd067a00255426bc697
active boot switches: -d:release -d:danger
```

**Comment by ghost** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/15027
