### ISSUE TITLE
`moveFile` wrongly accepts dirs, `moveDir` wrongly accepts files, contradicting docs

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16388]
### Example
```nim
import os
createDir("/tmp/d21/foo")
writeFile("/tmp/d21/z01.txt", "test")
moveFile("/tmp/d21/foo", "/tmp/d21/foo2") # this should fail
# moveDir("/tmp/d21/z01.txt", "/tmp/d21/z01b.txt") # this should also fail
```

### Current Output
works

### Expected Output
* `moveFile("/tmp/d21/foo", "/tmp/d21/foo2")` should raise ValueError since `"/tmp/d21/foo"` is a dir, not file
* `moveDir("/tmp/d21/z01.txt", "/tmp/d21/z01b.txt")` should also fail since `"/tmp/d21/z01.txt"` is a file, not a dir

### Additional Information
devel 1.5.1 5d8f862bc644e1db076e7e8cc8a2fe8c99009329
moveFile bug found while reviewing https://github.com/nim-lang/fusion/pull/53#discussion_r545559309

this is wrong for several reasons:
* it's right there in the name and the contradicts docs:
```nim
proc moveFile(source, dest: string) {...}
Moves a file from source to dest.

If this fails, OSError is raised. If dest already exists, it will be overwritten.

Can be used to rename files.
```

* there's a already moveDir
* this violates os.nim convention: path for file|dir, file for file, dir for dir
* it's error prone; user expects this to fail if passing a dir instead of a file so doesnt' do his own error checking, but then call succeeds and violates his expectations, potentially damaging filesystem

And now, I wonder what other procs in os.nim have this bug... 

Generally speaking, exceptions are the only sane way to handle user / io errors, and they're underused in os.nim; I'd rather have something raise (and fail early) then cause further damage with hard to find bugs because the bug happens long after the un-throwing error.

the fix should use the usual `-d:nimLegacyOsIgnoreFileVsDir` for fallback and raise an exception with the usual runtime contextual info

**Comment by juancarlospaco** [comment]
This needs a test that checks all file-only procs with folders and all folder-only procs with files, from `os` module.

**Comment by Araq** [comment]
That's quite picky. These procs promise they work for files/dirs but since they delegate to the OS, maybe more combinations are allowed. IMHO there is nothing to fix here.

**Comment by jrfondren** [comment]
All that you're asking for with these checks is blindness to the race condition: that a path tests as a file but is a dir by the time it's renamed. I'd fix this in the direction of correcting the documentation:

1. these procs try to perform a `rename` syscall, which is optimal (no copying, no ability for other procs to observe an incomplete file) but limited (only possible within the same filesystem)
2. and if `rename` fails due to its limitations, they'll try more expensive methods that definitely only work with either a file or a directory, by the name

EDIT: and then I actually looked at the docs, and they don't say enough to be wrong about anything. The expectation "this says moveFile so it shouldn't work on dirs" is more wrong than std.os is, here.

**Comment by juancarlospaco** [comment]
```python
import os, shutil
os.mkdir("folder")
assert os.path.isdir("folder")
assert not os.path.isfile("folder")
shutil.copyfile("folder", "nope")
```

```console
$ python example.py
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    shutil.copyfile("folder", "nope")
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

IsADirectoryError: [Errno 21] Is a directory: 'folder'
```

---
```python
import os, shutil
open("filename.txt", "w").close()
assert not os.path.isdir("filename.txt")
assert os.path.isfile("filename.txt")
shutil.copytree("filename.txt", "folder")
```

```console
$ python example.py
Traceback (most recent call last):
  File "/home/juan/code/temp4/example.py", line 10, in <module>
    shutil.copytree("filename.txt", "folder")
  File "/usr/lib/python3.9/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:

NotADirectoryError: [Errno 20] Not a directory: 'filename.txt'
```


@timotheecour How D does it?, crashes?, takes folders as files?, some other behavior?, we need an `osutils` ?.

**Comment by jrfondren** [comment]
>shutil.copyfile

copy, not move

>shutil.copytree

copy, not move.

Operating systems have very desirable 'move' operations which don't care (on Unix and Windows and surely others) about whether what they're moving is a file or directory. This doesn't extend to 'copy' operations.

The errors in Python's copy operations *also* do not come from separate checks which would just invite race conditions, but from the necessary operations failing on the inappropriate object.

**Comment by juancarlospaco** [comment]
But Nim has `copyFile` and `copyDir`. :shrug:

**Comment by jrfondren** [comment]
Yes, but this ticket is about moveFile and moveDir.

**Comment by juancarlospaco** [comment]
```nim
import os
discard existsOrCreateDir("abc") # imagine that theres already a folder "abc" that you must not remove.
writeFile("abc", "a")
```

```
Error: unhandled exception: [IOError]
```
