### ISSUE TITLE
js: parseJson doesn't work properly with large numbers

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17490]
### Example
```nim
import std/json

let a = "18446744073709551615"
let b = a.parseJson
echo b.kind
let c = $b
echo b # fails
```

### Current Output
```
JString
/Users/timothee/git_clone/nim/timn/build/nimcache/t12061.js:171
                  var code_33556847 = c_33556834.toString(16);
                                                 ^

TypeError: Cannot read property 'toString' of undefined
    at toJSStr (/Users/timothee/git_clone/nim/timn/build/nimcache/t12061.js:171:50)
    at rawEcho (/Users/timothee/git_clone/nim/timn/build/nimcache/t12061.js:481:16)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/build/nimcache/t12061.js:5599:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

### Expected Output
18446744073709551615

### Additional Information
1.5.1 28221e8a33e111d8653c4ff21fad47a7ec6ef54d
found while working on https://github.com/nim-lang/Nim/pull/17469

in js:
```
a="18446744073709551615"
b = JSON.parse(a)
console.log(typeof(b), b)

prints:
number 18446744073709552000
```

the question is what to do here:
option 1: do as js (and give approximate result)
option 2: raise an exception
option 3: check that the number represents a safe js integer, and if not, use `newJRawNumber`

## note
1.4.4 gives:
JInt
18446744073709552000

**Comment by timotheecour** [comment]
@xflywind IMO it's a half-regression instead of a regression; IMO we should go for option 3, which is the sanest:
this will make the output be `18446744073709551615` instead of approximate `18446744073709552000` as in 1.4.4
