### ISSUE TITLE
big int regression JS: Cannot mix BigInt and other types, use explicit conversions

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#21735]
ref https://github.com/nim-lang/checksums/pull/2

```
C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:1111
    result_687865870 = nimCopy(result_687865870, {Field0: x_687865869 >>> 0, Field1: 0}, NTI687865859);
                                                                      ^

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at fromUint64_687865868 (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:1111:71)
    at initShaContextVariant_671088807 (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:1130:64)
    at shaInitState_671088804 (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:1210:54)
    at initSha_671089910 (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:1276:50)
    at initShaStateStatic_671089932 (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:1289:50)
    at secureHash_536870916 (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:2468:26)       
    at Object.<anonymous> (C:\Users\blue\Documents\checksums\tests\crypto\tsha2.js:2753:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```
ref https://github.com/nim-lang/checksums/actions/runs/4818937469/jobs/8581532897?pr=2

**Comment by metagn** [comment]
Shouldn't be a Nim issue, linked PR uses bad FFI

```nim
proc forceUnsigned*(x: uint64): uint32 {.importjs: "# >>> 0".}
```

This is bad codegen for bigints, they do not support `>>>` and require `0n` instead of `0`. They are already unsigned too, it should just be a template with `forceUnsigned(uint32(x))` (maybe conditionally with something like [this](https://github.com/nim-lang/Nim/blob/220b45048983998675df761d4f33cd31128f10d5/lib/std/private/jsutils.nim#L86)).

Also the `--jsbigint64:off` switch exists

(Sidenote: The linked PR talks about `JsBigInt` arrays generating `Int32Array` which is still an issue because `JsBigInt` was unchanged and still uses `int`, we can fix this by checking `$t.sym.loc.r == "bigint"` for `tyInt` [here](https://github.com/nim-lang/Nim/blob/220b45048983998675df761d4f33cd31128f10d5/compiler/jsgen.nim#L1832) like in [here](https://github.com/nim-lang/Nim/blob/220b45048983998675df761d4f33cd31128f10d5/compiler/jsgen.nim#L1864) and giving `"Array"` instead)

**Comment by ringabout** [comment]
Make sense.
