### ISSUE TITLE
String slicing broken in the JS backend

### ISSUE THREAD

**Issue by bogen** [nim-lang/Nim#3120]
Given this nim compiler, built fresh this morning from github, same results with older nim compilers though:

```text
$ nim --version
Nim Compiler Version 0.11.2 (2015-07-15) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 45b6082c12dd6fc90a3dd3ca97e1ba157c3d6464
active boot switches: -d:release
```
And this slices.nim source file:
```nim
const someString = "Bananas Oranges Lemons Watermelons"

echo someString [ 5 .. 10 ]
```
With C it compiles:
```text
$ nim c slices.nim 
config/nim.cfg(53, 3) Hint: added path: '/home/dwight/.babel/pkgs/' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/dwight/.nimble/pkgs/' [Path]
Hint: used config file '/home/dwight/langscratch/nimrod/install/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: slices [Processing]
CC: slices
CC: stdlib_system
[Linking]
Hint: operation successful (9078 lines compiled; 2.009 sec total; 14.143MB; Debug Build) [SuccessX]
```

And runs fine:
```
$ ./slices 
as Ora
```

With JS it compiles:
```text
 $ nim js -o:slices.js slices.nim 
config/nim.cfg(53, 3) Hint: added path: '/home/dwight/.babel/pkgs/' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/dwight/.nimble/pkgs/' [Path]
Hint: used config file '/home/dwight/langscratch/nimrod/install/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: slices [Processing]
Hint: operation successful (4364 lines compiled; 0.419 sec total; 3.358MB; Debug Build) [SuccessX]
```

But pukes when I run it:
```text
$ node slices.js 
/home/dwight/langscratch/nimrod/js/slices.js:318
EX5BHEX5D_11254(cstrToNimstr("Bananas Oranges Lemons Watermelons"), HEX2EHEX2E
                                                                    ^
ReferenceError: HEX2EHEX2E_14006 is not defined
    at Object.<anonymous> (/home/dwight/langscratch/nimrod/js/slices.js:318:78)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I've been using Nim to develop some web apps and ran into the string slicing issue and was able to work around it, but proper string slicing would be best.

With the JS backend I am able to do other string access though.

Given this slices2.nim source file

```nim
import strutils

proc consoleprint (str:cstring): void {.importc: "print", noDecl.}
proc print (a: varargs[string, `$`]) = consoleprint (join (a, " "))

const someString = "Bananas Oranges Lemons Watermelons"

print someString

for i in 5 .. 10:
  print i, someString [i]

print someString [ 5 .. 10 ]
```
Which compiles fine:
```text
$ nim js -o:slices2.js slices2.nim
config/nim.cfg(53, 3) Hint: added path: '/home/dwight/.babel/pkgs/' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/dwight/.nimble/pkgs/' [Path]
Hint: used config file '/home/dwight/langscratch/nimrod/install/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: slices2 [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: operation successful (6259 lines compiled; 0.466 sec total; 6.614MB; Debug Build) [SuccessX]
```
But only partially runs:
```text
$ d8 slices2.js 
Bananas Oranges Lemons Watermelons
5 a
6 s
7  
8 O
9 r
10 a
slices2.js:449: ReferenceError: HEX2EHEX2E_23032 is not defined
EX5BHEX5D_11254(cstrToNimstr("Bananas Oranges Lemons Watermelons"), HEX2EHEX2E
                                                                    ^
ReferenceError: HEX2EHEX2E_23032 is not defined
    at slices2.js:449:83
```
Because I can iterate the slice indices, I can work around this issue for now.

**Comment by Araq** [comment]
Works on devel, tested it via ``nim js -d:nodejs -r temp.nim``

**Comment by bogen** [comment]
Confirmed. This is working with the latest devel. I should have done that earlier.

```text
nim --version
Nim Compiler Version 0.11.3 (2015-07-15) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 6c8e9da9ee8173091931980b64aa21a839fc1424
active boot switches: -d:release
```

Compiles:
```text
nim js -o:slices2.js slices2.nim
config/nim.cfg(53, 3) Hint: added path: '/home/dwight/.babel/pkgs/' [Path]
config/nim.cfg(54, 3) Hint: added path: '/home/dwight/.nimble/pkgs/' [Path]
Hint: used config file '/home/dwight/langscratch/nimrod/dinstall/build/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: slices2 [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: operation successful (6437 lines compiled; 0.432 sec total; 6.614MB; Debug Build) [SuccessX]
```
and runs:
```text
$ d8 slices2.js 
Bananas Oranges Lemons Watermelons
5 a
6 s
7  
8 O
9 r
10 a
as Ora
```
