### ISSUE TITLE
Issue with javascript compiler, var parameters and case fields

### ISSUE THREAD

**Issue by Arnaz87** [nim-lang/Nim#6612]
This snippet of code runs well on the native compiler, but doesn't work when js compiled

~~~nim
proc fillWith(sq: var seq[int], n: int, unused: string) =
  # It's skipping the *n* parameter
  # the string "unused" is being saved in *n*
  # and *unused* is undefined

  # TypeError: Cannot read property 'length' of undefined
  # echo "unused: ", unused

  echo "Fill with the number ", n
  sq = @[n]

type
  Object = object of RootObj
    case hasNums: bool
    of true:
      numbers: seq[int]
    of false:
      discard
    always: seq[int]

var obj = Object(hasNums: true)

# Works, because *always* does not depend on a case field
obj.always.fillWith(5, "unused")
echo obj.always

# Doesn't work, because *numbers* depends on *hasNums*
obj.numbers.fillWith(3, "unused")
echo obj.numbers
~~~

Output of `nim c -r main.nim`:
~~~
Fill with the number 5
@[5]
Fill with the number 3
@[3]
~~~

Output of `nim js -r main.nim`:
~~~
Fill with the number 5
@[5]
Fill with the number 117,110,117,115,101,100,0
/.../nimcache/main.js:385
		sq_25007[sq_25007_Idx] = nimCopy(null, [n_25008], NTI25023);
		                       ^

TypeError: Cannot set property '3' of null
    at fillWith_25003 (/.../nimcache/main.js:385:26)
    at Object.<anonymous> (/.../nimcache/main.js:632:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
~~~

`Nim Compiler Version 0.17.2 (2017-09-11) [Linux: i386]`

**Comment by Arnaz87** [comment]
These are the interesting parts in the generated JS:

~~~ javascript
// ...

var obj_25031 = [{hasNums: true, m_type: NTI25025, numbers: null, always: null}];

function fillWith_25003(sq_25007, sq_25007_Idx, n_25008, unused_25009) {
	var F={procname:"main.fillWith",prev:framePtr,filename:"main.nim",line:0};
	framePtr = F;
		F.line = 9;
		rawEcho(makeNimstrLit("Fill with the number "), cstrToNimstr((n_25008)+""));
		F.line = 10;
		sq_25007[sq_25007_Idx] = nimCopy(null, [n_25008], NTI25023);
	framePtr = F.prev;
}

fillWith_25003(obj_25031[0], "always", 5, makeNimstrLit("unused"));

// This is the one that's failing
fillWith_25003(obj_25031[0].numbers, 3, makeNimstrLit("unused"));

// Seems like this should be the actual output
// fillWith_25003(obj_25031[0], "numbers", 3, makeNimstrLit("unused"));

// ...
~~~

Apparently *fillWith* expects, in place of the single var parameter, the parent object plus the name of the field of that object, but apparently when that field depends on a discriminant, the compiler is just evaluating the field instead like it wasn't *var*.
