### ISSUE TITLE
Undefined Behavior when using const/let tables (Nim v0.18.1)

### ISSUE THREAD

**Issue by Drakoriss** [nim-lang/Nim#7332]
In new version of Nim I've got different results when trying to receive values from table:
```nim
import tables
const tableOfArray = {
    "one": [true, false, false],
    "two": [false, true, false],
    "three": [false, false, true]
}.toTable()
for i in 0..2:
    echo tableOfArray["two"][i]
```
Code above must print `false true false` to console, but instead it can return all values as false. Or fall into infinity loop. Or throw exception. Anything but proper result.
Same if I change `const` to `let`. But it works when I use `var`:
```nim
var tableOfArray = {
    "one": [true, false, false],
    "two": [false, true, false],
    "three": [false, false, true]
}.toTable()
```
When I use sequence instead of array it works too:
```nim
const tableOfArray = {
    "one": @[true, false, false],
    "two": @[false, true, false],
    "three": @[false, false, true]
}.toTable()
````

**Comment by Yardanico** [comment]
@Drakoriss this is intended behaviour, tables don't guarantee that you get items from a table by iterating over its values in the order you put them in. Use OrderedTable for behaviour you want.

**Comment by dom96** [comment]
Undefined behaviour is definitely not intended behaviour.

**Comment by Drakoriss** [comment]
@Yardanico What if I don't really care about order of output? I just need to iterate over such table but still got everything as `false` or even can catch infinity loop. But thanks for suggestion!

**Comment by BopoHDark** [comment]
Just note that behavior described above is true for MacOS and Linux, this code works as expected on the Windows platform.

**Comment by skilchen** [comment]
I consistently get the correct result (`false, true, false`) on Ubuntu 16.04 LTS using:
```
Nim Compiler Version 0.18.1 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: cc5140d8b6ea8ca65ec9b74348cf23aec09d6723
active boot switches: -d:release
```
and
```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
```

**Comment by Yardanico** [comment]
Did someone manage to reproduce it? I couldn't with clang on linux

**Comment by trustable-code** [comment]
Nim Compiler Version 0.18.0 [Linux: amd64]:
false
true
false
*** stack smashing detected ***: <unknown> terminated
No stack traceback available
SIGABRT: Abnormal termination.

**Comment by Drakoriss** [comment]
Updated Nim today:
```
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: cc5140d8b6ea8ca65ec9b74348cf23aec09d6723
active boot switches: -d:release
```
still exists for me (gotta interrupt execution because it's infinitely outputs `true`:
```
$ nim c -r main.nim
false
true
...
true^Ctrue
true
Traceback (most recent call last)
main.nim(10)             main
sysio.nim(430)           echoBinSafe
SIGINT: Interrupted by Ctrl-C.
```

**Comment by Araq** [comment]
I can reproduce it on OSX. And it's indeed a stack corruption so that the for loop variable gets overwritten producing and endless loop. Now why that stack corruption happens is still a mystery to me.

**Comment by Parashurama** [comment]
Using ``nim  --passC: '-fsanitize=address' --passL:' -lasan' `` with clang/gcc on Linux AMD64
and running with
``LD_PRELOAD=/usr/lib/libasan.so.4 ./test_table_undefined``
I got more details on the stack corruption
Also it shows the same issue, with const, let or var versions.
```nim
# reduced version
var tableOfArray = {
    "one": [true, false, false],
    "two": [false, true, false],
    "three": [false, false, true]
}.toTable()
echo tableOfArray.getOrDefault("one")
```

here is the stacktrace output
```
$ LD_PRELOAD=/usr/lib/libasan.so.4 ./test_table_undefined
=================================================================
==13013==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe1ecc4fe3 at pc 0x7fc75455c1fe bp 0x7ffe1ecc4e10 sp 0x7ffe1ecc45b8
WRITE of size 8 at 0x7ffe1ecc4fe3 thread T0
    #0 0x7fc75455c1fd in __asan_memset /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:428
    #1 0x557de2e67238 in getOrDefault_Sn6Mz12LoMCq3Pj41J13mg /folder/path/nimcache/stdlib_tables.c:737
    #2 0x557de2e48a22 in NimMainModule /folder/path/nimcache/test_table_undefined.c:197
    #3 0x557de2e48858 in NimMainInner /folder/path/nimcache/test_table_undefined.c:171
    #4 0x557de2e48c1c in NimMain /folder/path/nimcache/test_table_undefined.c:179
    #5 0x557de2e48d73 in main /folder/path/nimcache/test_table_undefined.c:186
    #6 0x7fc753baaf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #7 0x557de2e48429 in _start (/folder/path/test_table_undefined+0x6429)

Address 0x7ffe1ecc4fe3 is located in stack of thread T0 at offset 67 in frame
    #0 0x557de2e4886f in NimMainModule /folder/path/nimcache/test_table_undefined.c:190

  This frame has 2 object(s):
    [32, 40) 'T1_:191'
    [64, 67) 'T2_:192' <== Memory access at offset 67 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:428 in __asan_memset
Shadow bytes around the buggy address:
  0x100043d909a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d909b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d909c0: 00 00 00 00 f1 f1 f1 f1 00 00 f2 f2 00 f3 f3 f3
  0x100043d909d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d909e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100043d909f0: 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2[03]f3 f3 f3
  0x100043d90a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d90a10: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f3 f3 f3
  0x100043d90a20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d90a30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100043d90a40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13013==ABORTING
```

**Comment by Parashurama** [comment]
I think I found the issue:

In proc:
```nim
{.emit: """/*INCLUDESECTION*/
#include <stdio.h>
""".}
proc crashingProc*[B](t: seq[B], index: Natural): B =
    {.emit: ["""fprintf(stdout, "C:sizeof:%d\n", (int)sizeof(""", result, "));"].}
    echo "N:sizeof", sizeof(result)
    discard

```
which translate to

```C
N_LIB_PRIVATE N_NIMCALL(void, crashingProc_32RzIjpmCbnI2n4KIEf20g)(tySequence_ijtzneBXRouS2n9a7Rvf7dg* t, NI index, tyArray_xSxqoPo7Fj4uIDcWiYyWDg Result) {
	tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	fprintf(stdout, "C:sizeof:%d\n", (int)sizeof(Result));
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString(((NimStringDesc*) &TM_Is5bcFTKJBXGUbrkjXBdPQ_5));
	T1_[1] = nimIntToStr(((NI)sizeof(tyArray_xSxqoPo7Fj4uIDcWiYyWDg)));
	echoBinSafe(T1_, 2);
}
```
Size of Result is 8
while sizeof(type of result) is 3 which is the expected result.
It's probably an issue of array pased as argument decaying into a pointer which has size 8 on x64 instead of mesuring the total bytes size of the array.

The solution seems to be using sizeof(type of result) for memset.

**Comment by Araq** [comment]
Yup, that's it.
