### ISSUE TITLE
HttpClient: requesting URL with no scheme fails

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7842]
```nim
import httpclient

var client = newHttpClient()
client.getContent("google.com").echo
```

```
a10.nim(4)               a10
httpclient.nim(1237)     getContent
httpclient.nim(1226)     get
httpclient.nim(1218)     request
httpclient.nim(1195)     request
httpclient.nim(1164)     requestAux
httpclient.nim(1106)     newConnection
net.nim(1606)            dial
oserr.nim(66)            raiseOSError
Error: unhandled exception: Connection refused [OSError]
```

**Comment by enthus1ast** [comment]
Without scheme it is relative. Should it be https then http? 
I think it should throw an exception telling the user to supply the scheme

**Comment by genotrance** [comment]
@enthus1ast can you submit a PR? Then this issue can be closed.

**Comment by enthus1ast** [comment]
@genotrance i had but it got closed https://github.com/nim-lang/Nim/pull/7846

**Comment by dom96** [comment]
```
~ » curl -v google.com
* Rebuilt URL to: google.com/
*   Trying 216.58.214.14...
* Connected to google.com (216.58.214.14) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Fri, 19 Oct 2018 22:49:29 GMT
< Expires: Sun, 18 Nov 2018 22:49:29 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact

```

``curl`` assumes "http", IMO it's fine to do the same. Can we get a PR that does this?

**Comment by enthus1ast** [comment]
assuming http is dangerous
and nobody else does it
see:

python (requires sheme):

```python
import urllib.request
urllib.request.urlopen("google.de")       
# ValueError: unknown url type: 'google.de'
```

perl (requires sheme):
```perl
require LWP::UserAgent;
my $ua = LWP::UserAgent->new;
my $response = $ua->get('google.de');
if ($response->is_success) {
    print $response->decoded_content;  # or whatever
}
else {
    die $response->status_line;
}
# 400 URL must be absolute at - line 12.
```


go (requires sheme): 

```go
package main

import (
	"net/http"
	"log"
	"io/ioutil"
)

func main() {
	MakeRequest()
}

func MakeRequest() {
	resp, err := http.Get("google.de")
	if err != nil {
		log.Fatalln(err)
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}

	log.Println(string(body))
}
# 2018/10/20 02:37:38 Get google.de: unsupported protocol scheme ""
# exit status 1
```


javascript/nodejs (requires sheme):

```javascript
const https = require('https');

https.get('https://google.de', (resp) => {
  let data = '';

  // A chunk of data has been recieved.
  resp.on('data', (chunk) => {
    data += chunk;
  });

  // The whole response has been received. Print out the result.
  resp.on('end', () => {
    console.log(JSON.parse(data).explanation);
  });

}).on("error", (err) => {
  console.log("Error: " + err.message);
});

// Error: Unable to determine the domain name
//     at Object.request (https.js:233:13)
//     at Object.get (https.js:247:21)
// > 
```

javascript/nodejs/request (requires sheme)

```javascript
const request = require('request');

request('google.de', { json: true }, (err, res, body) => {
  if (err) { return console.log("ERROR", err); }
  console.log(body.url);
  console.log(body.explanation);
});
// ERROR Error: Invalid URI "google.de"
```

javascript/browser/XMLHttprequest (think its same domain -> requires sheme)
```javascript
var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
       // Typical action to be performed when the document is ready:
       document.getElementById("demo").innerHTML = xhttp.responseText;
    }
};
xhttp.open("GET", "google.de", true);
xhttp.send();

// VM102:9 GET https://www.google.de/google.de 404 
```
