### ISSUE TITLE
Large HeapQueue SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by mboratko** [nim-lang/Nim#8058]
Here is a minimal working example:

```
import sequtils
import HeapQueue

var nums = toSeq(0..100_000_000)

var pq = newHeapQueue[int]()
var start = 1_000_000
for size in countup(start, 100_000_000, 10000):
    pq = newHeapQueue[int]()
    for i in 0..size:
        pq.push(nums[i])
    echo pq.len()
```

This results in

```
1000001
1010001
1020001
1030001
~ (snip) ~
2030001
Traceback (most recent call last)
sigsegv.nim(11)          sigsegv
heapqueue.nim(73)        push
gc.nim(586)              growObj
gc.nim(525)              growObj
alloc.nim(850)           rawDealloc
alloc.nim(549)           freeBigChunk
alloc.nim(217)           addChunkToMatrix
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

(The exact iteration at which this happens is not always the same.)

Changing `start` leads to different results.

With `start = 3_000_000` I get

```
3000001
~ (snip) ~
3510001
3520001
sigsegv.nim(11)          sigsegv
system.nim(2833)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

But then with `start = 6_000_000` I'm back to getting this error:

```
6000001
6010001
~ (snip) ~
6260001
6270001
Traceback (most recent call last)
sigsegv.nim(11)          sigsegv
heapqueue.nim(73)        push
gc.nim(586)              growObj
gc.nim(537)              growObj
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by mratsim** [comment]
What Nim version/commit are you using? (This is the output of `nim -v`).

I tried the first example, and left my CPU running for 30s and "long" past 2030001, but it didn't crash.

I'm pretty sure `addChunkToMatrix` and `growObj` were solved by https://github.com/nim-lang/Nim/pull/7338 as I regularly hit the same kind of crashes in the past https://github.com/mratsim/Arraymancer/issues/178.

**Comment by mboratko** [comment]
Output of nim-v:

```
Nim Compiler Version 0.18.0 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 855956bf617f68ac0be3717329e9e1181e5dc0c6
active boot switches: -d:release
```

**Comment by pb-cdunn** [comment]
Did that solve your problem? We might have the same problem, but we're on a May 15 commit, so we already have the fix from #7338.

**Comment by pb-cdunn** [comment]
```
Thread 1 "fc_rr_hctg_trac" received signal SIGSEGV, Segmentation fault.
0x000000000040ae83 in addChunkToMatrix_v9bekLOkesgfrZC4aumfLXw (a=0x673060 <mainThread_6r3APOnKvB9aL9atazGvT52A+160>, b=0x7ffe3010c000)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/alloc.nim:220
220    nim/0.18.1/Nim/lib/system/alloc.nim: Datei oder Verzeichnis nicht gefunden.
```
I'm trying to get a full backtrace ...

**Comment by pb-cdunn** [comment]
(This program is single-threaded, so I do not understand the crash.)
```nim
#0  0x000000000040ae83 in addChunkToMatrix_v9bekLOkesgfrZC4aumfLXw (a=0x673060 <mainThread_6r3APOnKvB9aL9atazGvT52A+160>, b=0x7ffe3010c000)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/alloc.nim:220
#1  0x000000000040afb6 in splitChunk_8QXhiy717OAl8WNA2X27EA (a=0x673060 <mainThread_6r3APOnKvB9aL9atazGvT52A+160>, c=0x7ffe3010b000, size=4096)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/alloc.nim:543
#2  0x000000000040b44a in getBigChunk_z9bCNjXTYllZ3pI24nEsw2g (a=0x673060 <mainThread_6r3APOnKvB9aL9atazGvT52A+160>, size=4096)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/alloc.nim:599
#3  0x000000000040b552 in getSmallChunk_h6cvXbfQjxIdThM5GthosA (a=0x673060 <mainThread_6r3APOnKvB9aL9atazGvT52A+160>) at /mnt/software/n/nim/0.18.1/Nim/lib/system/alloc.nim:628
#4  0x000000000040c0d7 in rawAlloc_yn9c8RLaS8vgVBeMBfmkdUg (a=0x673060 <mainThread_6r3APOnKvB9aL9atazGvT52A+160>, requestedSize=43)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/alloc.nim:751
#5  0x0000000000413be9 in rawNewObj_QBPo5VW2O56Eeh8hPbQ7Pg (typ=0x677280 <strDesc_D0UzA4zsDu5tgpJQ9a9clXPg>, size=27, gch=0x673000 <mainThread_6r3APOnKvB9aL9atazGvT52A+64>)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/gc.nim:446
#6  0x0000000000413cab in newObjNoInit (typ=0x677280 <strDesc_D0UzA4zsDu5tgpJQ9a9clXPg>, size=27) at /mnt/software/n/nim/0.18.1/Nim/lib/system/gc.nim:471
#7  0x0000000000413d04 in rawNewStringNoInit (space=10) at /mnt/software/n/nim/0.18.1/Nim/lib/system/sysstr.nim:77
#8  0x0000000000413d67 in copyString (src=0x7ffeb4cb1228) at /mnt/software/n/nim/0.18.1/Nim/lib/system/sysstr.nim:124
#9  0x0000000000418b79 in genericAssignAux_T3cq9aUp9bgGOBuyUSWGriTA (dest=0x7ffe3010aff0, src=0x7ffeb4cb20f0, mt=0x6770a0 <NTI_77mFvmsOLKik79ci2hXkHEg_>, shallow=0 '\000')
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:54
#10 0x000000000041858e in genericAssignAux_ulsQvfENf9buS9atYunbm7gA (dest=0x7ffe3010afe8, src=0x7ffeb4cb20e8, n=0x66c520 <TM_0JXiWyhP5OCO8jWMA6sb1w_0.3371+192>, shallow=0 '\000')
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:21
#11 0x0000000000418656 in genericAssignAux_ulsQvfENf9buS9atYunbm7gA (dest=0x7ffe3010afe8, src=0x7ffeb4cb20e8, n=0x66c4c0 <TM_0JXiWyhP5OCO8jWMA6sb1w_0.3371+96>, shallow=0 '\000')
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:24
#12 0x0000000000419209 in genericAssignAux_T3cq9aUp9bgGOBuyUSWGriTA (dest=0x7ffe3010afe8, src=0x7ffeb4cb20e8, mt=0x685ee0 <NTI_QeWl6B6ffS4pU6WWrtcrDw_>, shallow=0 '\000')
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:100
#13 0x0000000000419011 in genericAssignAux_T3cq9aUp9bgGOBuyUSWGriTA (dest=0x7ffeb8e325b0, src=0x7fffffffc9c8, mt=0x685f40 <NTI_4eRCaZmrYLLw2k30GPTiMw_>, shallow=0 '\000')
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:78
#14 0x00000000004195c5 in genericAssign (dest=0x7ffeb8e325b0, src=0x7fffffffc9c8, mt=0x685f40 <NTI_4eRCaZmrYLLw2k30GPTiMw_>)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:124
#15 0x0000000000419649 in genericSeqAssign (dest=0x7ffeb8e325b0, src=0x7ffeb4cb20a8, mt=0x685f40 <NTI_4eRCaZmrYLLw2k30GPTiMw_>)
    at /mnt/software/n/nim/0.18.1/Nim/lib/system/assign.nim:161
#16 0x000000000042f2c3 in rawInsert_gxkqTO0qUiX19cBJNNrDhqQ (t=0x7ffff7f5de88, data=0x7ffff7f5de88, key=0x7ffeb4cb11f8, val=..., hc=5458867906957517099, h=1810731)
    at /mnt/software/n/nim/0.18.1/Nim/lib/pure/collections/tableimpl.nim:65
#17 0x000000000042f77c in enlarge_HhcG5lD9ciY9cb7QYJL89chbQ (t=0x7ffff7f5de88) at /mnt/software/n/nim/0.18.1/Nim/lib/pure/collections/tables.nim:308
#18 0x000000000042fbc1 in X5BX5Deq__BNMUZTRGOlK6FF22pAEt8Q (t=0x7ffff7f5de88, key=0x7ffeabeb12e8, val=...) at /mnt/software/n/nim/0.18.1/Nim/lib/pure/collections/tableimpl.nim:90
#19 0x000000000042fd03 in X5BX5Deq__9bsYqwCXj0XzW0Wjhn4SDSQ (t=0x7ffff7f5de88, key=0x7ffeabeb12e8, val=...) at /mnt/software/n/nim/0.18.1/Nim/lib/pure/collections/tables.nim:452
#20 0x0000000000421cea in stream_get_rid_to_ctg_KsGZQeWW9a4A9b5wkpoWGMLg (ss=0x7ffff7f944c8, fn=0x7ffff7f70128)
    at /localdisk/scratch/cdunn/repo/nim-falcon/src/falcon/rr_hctg_track.nim:192
#21 0x0000000000423cc7 in get_rid_to_ctg_5k9as9aF89csVMZfpuwG75G4A (fn=0x7ffff7f70128) at /localdisk/scratch/cdunn/repo/nim-falcon/src/falcon/rr_hctg_track.nim:216
#22 0x00000000004241fe in run_stage2_tCeAPnuZmijslYWytH9bEhQ (test=0 '\000', read_to_contig_map=0x7ffff7f70128, partials_fn=0x7ffff7f71118, output=0x7ffff7f66db8, bestn=40,
    n_core=0, phased_read_file=0x7ffff7f5c9a8, rawread_ids=0x7ffff7f5cb38, min_len=2500, stream=0 '\000', debug=0 '\000', silent=0 '\000')
    at /localdisk/scratch/cdunn/repo/nim-falcon/src/falcon/rr_hctg_track.nim:524
#23 0x0000000000407443 in dispatchrun_stage2_q1v8HY0y8u9a1jF6wBjp9anA (cmdline=0x7ffff7f59048, doc=0x454d60 <TM_pV079aXDyspXn8Jn1rbhDpw_88>,
    usage=0x454da0 <TM_pV079aXDyspXn8Jn1rbhDpw_89>, prefix=0x454300 <TM_pV079aXDyspXn8Jn1rbhDpw_8>, subSep=0x454300 <TM_pV079aXDyspXn8Jn1rbhDpw_8>)
    at /localdisk/scratch/cdunn/repo/nim-falcon/repos/cligen/cligen.nim:231
#24 0x0000000000407b5f in NimMainModule () at /localdisk/scratch/cdunn/repo/nim-falcon/repos/cligen/cligen.nim:409
---Type <return> to continue, or q <return> to quit---
#25 0x0000000000407a5d in NimMainInner () at /mnt/software/n/nim/0.18.1/Nim/lib/system/threads.nim:411
#26 0x0000000000407a86 in NimMain () at /mnt/software/n/nim/0.18.1/Nim/lib/system/threads.nim:419
#27 0x0000000000407abf in main (argc=4, args=0x7fffffffddb8, env=0x7fffffffdde0) at /mnt/software/n/nim/0.18.1/Nim/lib/system/threads.nim:426
```

**Comment by pb-cdunn** [comment]
That's at commit 02f01470ab46067c18535605179b95b143b1e25f
```
commit 02f01470ab46067c18535605179b95b143b1e25f
Merge: c73cd53 f8e23da
Author: Araq <rumpf_a@web.de>
Date:   Tue May 15 06:29:48 2018

    Merge branch 'devel' into araq-big-refactoring
```

**Comment by pb-cdunn** [comment]
```
220         mat().prev = b
(gdb) print b
$1 = (tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg *) 0x7ffe379db000
(gdb) print *b
$2 = {Sup = {prevSize = 4096, size = 1275064320}, next = 0x4ee52000, prev = 0x0, data = 0}
(gdb) p a.matrix[fl][sl]
$3 = (tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg *) 0x4ee52000
(gdb) p *a.matrix[fl][sl]
Cannot access memory at address 0x4ee52000
(gdb) p fl
$4 = 24
(gdb) p sl
$5 = 5
```

**Comment by pb-cdunn** [comment]
```
(gdb) p *a.matrix[fl]
$3 = (tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg *) 0x7ffff7e12000
(gdb) p a.matrix[fl]
$4 = {0x7ffff7e12000, 0x1a107a000, 0x0, 0x4a4cd000, 0x1258bade0, 0x4962f000, 0x7ffff7e16dd8, 0x7ffff7e15108, 0x7ffff7e1a298,
  0x7ffff7e1be28, 0x7ffff7e1a5b8, 0x7ffff7e15568, 0x7ffff7e1a0b8, 0x7ffff7e15608, 0x7ffff7e159c8, 0x7ffff7e15248,
  0x7ffff7e15a18, 0x7ffff7e15b08, 0x7ffff7e15978, 0x7ffff7e158d8, 0x7ffff7e15b58, 0x7ffff7e156f8, 0x7ffff7e15a68,
  0x7ffff7e15518, 0x7ffff7e15d38, 0x7ffff7e157e8, 0x7ffff7e15e28, 0x7ffff7e15d88, 0x7ffff7e15ce8, 0x7ffff7e15c48,
  0x7ffff7e15ab8, 0x7ffff7e155b8}
```

**Comment by mratsim** [comment]
Maybe linked to #7894

**Comment by pb-cdunn** [comment]
This seems to be where a bad value comes from:
```nim
543     proc splitChunk(a: var MemRegion, c: PBigChunk, size: int) =
544       let rest = splitChunk2(a, c, size)
545       addChunkToMatrix(a, rest)
```
```
(gdb) p *c
$34 = {Sup = {prevSize = 0, size = 16777216}, next = 0x0, prev = 0x0, data = 0}
(gdb) p *rest
$35 = {Sup = {prevSize = 16777216, size = 1214443520}, next = 0x1258bade0, prev = 0x0, data = 0}
```

**Comment by pb-cdunn** [comment]
That worked for me.

**Comment by dom96** [comment]
So I assume this can be closed now.
