### ISSUE TITLE
[JS] setLen on nil seq crashes

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#9643]
```nim
var s: seq[int]
s.setLen(5)
```
```
nim js -r ~/test.nim
```
```
/home/yglukhov/nimcache/test.js:29
if (s_26004[0].length < 5) { for (var i=s_26004[0].length;i<5;++i) s_26004[0].push(0); }
               ^

TypeError: Cannot read property 'length' of null
    at Object.<anonymous> (/home/yglukhov/nimcache/test.js:29:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by krux02** [comment]
can you join all the seq related crashes for JS in one issues? They are very likely all solved at once and then it is easier if all the information is gathered in one issue.

**Comment by yglukhov** [comment]
I don't think they are solved literally "at once", that's why I've split those. But another "similar" issue is #9644

**Comment by krux02** [comment]
I think they are, because they are both a cause of the removal of the nil type. The js backend didn't catch up with the canges in the C/C++ backend.
